### ISSUE TITLE
error: import cv2

### ISSUE THREAD

**Issue by kimjsik08** [geaxgx/depthai_pipeline_graph#5]
My file works when I run it by itself, but when I run the pipeline graph on it, I get an error: 

```
Traceback (most recent call last):
  File "C:\Users\kimjs\PycharmProjects\OakD\depthai-python\examples\SpatialDetection\spatial_tiny_yolo.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

I'm confused about this error because I have cv2 installed, otherwise my file wouldn't open by itself. Thank you in advance!

**Comment by geaxgx** [comment]
If I understand correctly, you have no problem when you run directly the code, but you get the error when started via the pipeline_graph command. I wonder if the same python executable is used in both cases.
What are the exact command lines you used ?
Can you try with using the absolute path of the python exec ?
So something like: `pipeline_graph run "absolute_path_python spatial_tiny_yolo.py"`

**Comment by kimjsik08** [comment]
Thank you! Finding and using the absolute path of my venv python resolved the issue.
